# Generated by Django 4.2.7 on 2023-11-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('short_desc', models.TextField(max_length=20)),
                ('long_desc', models.TextField(max_length=100)),
                ('repo_url', models.URLField()),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
