# Generated by Django 4.2.7 on 2023-11-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='long_desc',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_desc',
            field=models.CharField(max_length=100),
        ),
    ]
