# Generated by Django 4.2.7 on 2023-12-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_thumbnail_alter_project_long_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
