# Generated by Django 4.2.7 on 2024-02-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_demo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='long_desc',
            field=models.CharField(max_length=2000),
        ),
    ]
